// <auto-generated />
namespace Back2Retro.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class retro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(retro));
        
        string IMigrationMetadata.Id
        {
            get { return "202505180002014_retro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
